matrix:
  scenario:
    - ember-lts-4.4
    - ember-lts-3.28
    - ember-release
    - ember-classic
    - embroider-safe

pipeline:
  ${scenario}:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm ci
      - npm run try:one --workspace test-app -- ${scenario}
    # Pipeline level conditions aren't supported yet:
    # https://github.com/woodpecker-ci/woodpecker/issues/283
    when:
      event:
        - pull_request

depends_on:
  - test