matrix:
  scenario:
    - ember-lts-3.28
    - ember-lts-4.8

pipeline:
  ${scenario}:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
      - npx ember try:one ${scenario}

when:
  event:
    - pull_request

depends_on:
  - test