name: 'pull-request'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled


jobs:
  changelog:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPENDABOT_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update the changelog
        uses: abeforgit/dependabot-changelog-helper@6ac73689e40c543f6b802f4c72b9c4f66053adf5
        with:
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'

      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update changelog [CI SKIP]"
          pull: '--rebase --autostash'
          commit: '--signoff'


 
