name: 'ensure-changelog'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled


jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: check changelog edits
        uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: dependabot, skip-changelog
